# Generated by Django 5.2.8 on 2025-11-28 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_resume_skills_resume_file_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoriteVacancy',
        ),
    ]
