# Generated by Django 5.2.8 on 2025-11-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_company'),
        ('api', '0005_favoritevacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='company',
            field=models.JSONField(blank=True, default=dict, help_text='Company info: {name, logo, description, website}', verbose_name='Company'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
