# Generated by Django 5.2.8 on 2025-11-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_vacancy_company_delete_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='company',
            field=models.CharField(blank=True, max_length=200, verbose_name='Company'),
        ),
    ]
