# Generated by Django 5.2.8 on 2025-11-29 11:04
# Modified to handle missing company field

from django.db import migrations, models


def add_company_field_if_missing(apps, schema_editor):
    """Add company field if it doesn't exist"""
    Vacancy = apps.get_model('api', 'Vacancy')
    db_table = Vacancy._meta.db_table
    
    # Check if column exists
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f"PRAGMA table_info({db_table})")
        columns = [row[1] for row in cursor.fetchall()]
        
        if 'company' not in columns:
            # Add the field as CharField
            cursor.execute(
                f"ALTER TABLE {db_table} ADD COLUMN company VARCHAR(200) DEFAULT ''"
            )


def reverse_add_company_field(apps, schema_editor):
    """Reverse migration - SQLite doesn't support DROP COLUMN easily"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_vacancy_company_delete_company'),
    ]

    operations = [
        migrations.RunPython(add_company_field_if_missing, reverse_add_company_field),
        migrations.AlterField(
            model_name='vacancy',
            name='company',
            field=models.CharField(blank=True, max_length=200, verbose_name='Company'),
        ),
    ]
